service:
  name: tweet-service


management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic:
    listening:
      name: tweets
    sending:
      name: filtered_teets


  brokers:
    "localhost:9092, localhost:9093"
server:
  port: 9081


